<a href="https://colab.research.google.com/github/Chong5084/Colab_Note/blob/main/ch05_04_%EA%B8%B0%EC%88%A0%ED%86%B5%EA%B3%84%2B%EB%82%9C%EC%88%98%EB%B0%9C%EC%83%9D%EA%B3%BC%2B%EC%B9%B4%EC%9A%B4%ED%8C%85_%EA%B3%B5%EC%9C%A0%EC%9A%A9_ipynb%EC%9D%98_%EC%82%AC%EB%B3%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 기술 통계

[링크 텍스트](https://)## 기술 통계(descriptive statistics)
> 데이터 집합에 대해 통계를 계산
* 데이터의 개수(count)
* 평균(mean, average)
* 분산(variance)
* 표준 편차(standard deviation)
* 최댓값(maximum)
* 최솟값(minimum)
* 중앙값(median)
* 사분위수(quartile)

In [3]:
import numpy as np

In [107]:
x = np.array([
    18, 5, 10, 23, 19, -8, 10, 0, 0, 5, 2, 15, 8,
    2, 5, 4, 15, -1, 4, -7, -24, 7, 9, -6, 23, -13
])
x

array([ 18,   5,  10,  23,  19,  -8,  10,   0,   0,   5,   2,  15,   8,
         2,   5,   4,  15,  -1,   4,  -7, -24,   7,   9,  -6,  23, -13])

## 데이터의 개수

In [5]:
len(x)

26

## 표본 평균
* 우리가 일반적으로 아는 평균
* 통계용어로는 표본 평균(sample average, sample mean)
<br>
$
\bar{x} = \frac{1}{N}\displaystyle\sum_{i=1}^{N}{x_i}
$
(𝑁은 데이터의 개수)

In [9]:
np.mean(x), x.mean()

(4.8076923076923075, 4.8076923076923075)

## 표본 분산
* 표본 분산(sample variance) : 데이터와 표본 평균간의 거리의 제곱의 평균
* 표본 분산이 작으면 데이터가 모여있는 것이고 크면 흩어져 있는 것
<br>
$
s^2 = \frac{1}{N}\displaystyle\sum_{i=1}^{N}{(x_i-\bar{x})^2}
$

In [12]:
#차이를 제곱한것
np.var(x), x.var()

(115.23224852071006, 115.23224852071006)

## 표본 표준편차
* 표본 표준편차(sample standard variance) : 표본 분산의 양의 제곱근 값
<br>
$
s = \sqrt{s^2}
$

In [14]:
np.std(x), x.std()

(10.734628476137871, 10.734628476137871)

## 최댓값과 최솟값

In [15]:
# 최댓값 (maximum) / 최솟값 (minimum)
np.max(x), x.min()

(23, -24)

## 중앙값
* 중앙값(median) : 데이터를 크기대로 정렬하였을 때 가장 가운데에 있는 수
* 만약 데이터의 수가 짝수이면 가장 가운데에 있는 두 수의 평균을 사용


In [ ]:
np.median(x) # 내장된 메소드 없음 x.median()

5.0

## 사분위수
* 사분위수(quartile) : 데이터를 가장 작은 수부터 가장 큰 수까지 크기가 커지는 순서대로 정렬하였을 때 1/4, 2/4, 3/4 위치에 있는 수
* 각각 1사분위수, 2사분위수, 3사분위수라고 함
* 1/4의 위치란 전체 데이터의 수가 만약 100개이면 25번째 순서, 즉 하위 25%
* 따라서 2사분위수는 중앙값과 같음
* 때로는 위치를 1/100 단위로 나눈 백분위수(percentile)을 사용하기도 함
* 1사분위수는 25% 백분위수와 같음


In [17]:
np.percentile(x, 0)  # 최솟값. min

-24.0

In [18]:
np.percentile(x, 25)  # 25% 백분위수, 1사분위수

0.0

In [ ]:
np.percentile(x, 50)  # 50% 백분위수, 2사분위수, 중앙값

5.0

In [ ]:
np.percentile(x, 75)  # 75% 백분위수, 3사분위수, 중앙

10.0

In [19]:
np.percentile(x, 100)  # 100% 백분위수, 4사분위수, 최댓값

23.0

# 난수 발생과 카운팅

## 시드 설정
* 컴퓨터 프로그램에서 발생하는 무작위 수는 사실 엄격한 의미의 무작위 수가 아님
* 어떤 특정한 시작 숫자를 정해 주면 컴퓨터가 정해진 알고리즘에 의해 마치 난수처럼 보이는 수열을 생성. 이런 시작 숫자를 시드(seed)라고 함
* 일단 생성된 난수는 다음번 난수 생성을 위한 시드값이 됨. 따라서 시드값은 한 번만 정해주면 됨.
* 시드는 보통 현재 시각 등을 이용하여 자동으로 정해지지만 사람이 수동으로 설정할 수도 있음 * 특정한 시드값이 사용되면 그 다음에 만들어지는 난수들은 모두 예측할 수 있음
* 고정된 결과를 얻기 위해서 실습엔 시드를 설정

In [27]:
np.random.seed(0) # 시드값 고정

### `rand` : 0과 1 사이의 난수를 발생

In [25]:
np.random.rand(5) # rand(n) : n개의 길이를 가지는 배열에 각각 0~1 사이의 난수를 채워줌

array([4.17022005e-01, 7.20324493e-01, 1.14374817e-04, 3.02332573e-01,
       1.46755891e-01])

In [23]:
np.random.rand(10)

array([0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606,
       0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215])

*이탤릭체 텍스트*## 데이터의 순서 변경

### `shuffle`
* 데이터의 순서를 변경
* 자체 변환(in-place) 함수 (원본에 영향)

In [29]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
np.random.shuffle(x) # x를 섞어줌 -> x 자체를 섞어버림
x

array([6, 1, 9, 2, 7, 5, 8, 0, 3, 4])

## 데이터 샘플링
* 표본선택 혹은 샘플링(sampling) : 이미 있는 데이터 집합에서 일부를 무작위로 선택하는 것

### `choice` : 샘플링에 사용
```
numpy.random.choice(a, size=None, replace=True, p=None)
```
* a : 배열이면 원래의 데이터, 정수이면 arange(a) 명령으로 데이터 생성
* size : 정수. 샘플 숫자
* replace : 불리언. True이면 한번 선택한 데이터를 다시 선택 가능 (복원/비복원 추출)
* p : 배열. 각 데이터가 선택될 수 있는 확률

In [32]:
np.random.choice(5, 5, replace=False)# 5개중 5개 선택 / 비복원 -> shiffle

array([0, 4, 2, 1, 3])

In [33]:
np.random.choice(5, 3, replace=False)# 5개중 3개 선택 / 비복원 -> shiffle

array([4, 2, 3])

In [37]:
# np.random.choice(5, 10) # 복원 5개 중 10개 선택 ( 뽑았던것을 또 뽑는다)
np.random.choice(5, 10, replace=True) # 5개 중 10개 선택 ( 뽑았던것을 또 뽑는다)

array([4, 0, 4, 1, 4, 1, 2, 2, 0, 1])

In [40]:
# [0, 1, 2, 3, 4] # p = 확률 약자
np.random.choice(5, 10, p=[0.1, 0, 0.3, 0.6, 0]) # 복원, 5개 중에 10개를 선택 (뽑았던 것을 또 뽑는다)

array([3, 0, 3, 3, 2, 2, 2, 2, 3, 3])

## 난수 생성
* `rand` : 0부터 1 사이의 균일 분포
* `randn` : 표준 정규 분포
* `randint` : 균일 분포의 정수 난수

### `rand` : 0부터 1 사이에서 균일한 확률 분포로 실수 난수를 생성
* 숫자 인수는 생성할 난수의 크기
* 여러 개의 인수를 넣으면 해당 크기를 가진 행렬을 생성

In [41]:
np.random.rand(10)

array([0.98837384, 0.10204481, 0.20887676, 0.16130952, 0.65310833,
       0.2532916 , 0.46631077, 0.24442559, 0.15896958, 0.11037514])

In [42]:
np.random.rand(3, 5) #여러 개의 인수를 넣으면 해당 크기를 가진 행렬을 생성

array([[0.65632959, 0.13818295, 0.19658236, 0.36872517, 0.82099323],
       [0.09710128, 0.83794491, 0.09609841, 0.97645947, 0.4686512 ],
       [0.97676109, 0.60484552, 0.73926358, 0.03918779, 0.28280696]])

### `randn` : 기댓값이 0이고 표준편차가 1인 표준 정규 분포(standard normal distribution)를 따르는 난수를 생성

In [43]:
np.random.randn(10) #

array([-0.36433431, -0.67877739, -0.35362786, -0.74074747, -0.67502183,
       -0.13278426,  0.61980106,  1.79116846,  0.17100044, -1.72567135])

In [44]:
np.random.randn(3, 5) # 3행 5열

array([[ 0.16065854, -0.85898532, -0.20642094,  0.48842647, -0.83833097],
       [ 0.38116374, -0.99090328,  1.01788005,  0.3415874 , -1.25088622],
       [ 0.92525075, -0.90478616,  1.84369153,  1.52550724, -1.44553558]])

### `randint`
```
numpy.random.randint(low, high=None, size=None)
```
만약 `high`를 입력하지 않으면 0과 `low`사이의 숫자, `high`를 입력하면 `low`와 `high`는 사이의 숫자를 출력. `size`는 난수의 숫자

In [111]:
# np.random.randint(10)  # 최대값 -> 그것보다 작은 범위에서의 랜덤 숫자
np.random.randint(10, size=1)  # 최대값 -> 그것보다 작은 범위에서의 랜덤 숫자

array([0])

In [68]:
np.random.randint(10, size=2) # 시작점

array([5, 7])

In [48]:
np.random.randint(10, 20, size=10)  # 시작점, 끝점

array([16, 19, 18, 10, 18, 15, 19, 10, 19, 16])

## 💡 연습문제 7
1. 동전을 10번 던져 앞면(숫자 1)과 뒷면(숫자 0)이 나오는 가상 실험을 작성하라
2. 주사위를 100번 던져서 나오는 숫자의 평균
3. 가격이 10,000원인 주식이 있다. 이 주식의 일간 수익률(%)은 기댓값이 0%이고 표준편차가 1%인 표준 정규 분포를 따른다고 하자. 250일 동안의 주가를 무작위로 생성하라

In [82]:
# 1.
np.random.choice(2, 10)


array([0, 1, 0, 1, 0, 0, 0, 1, 1, 1])

In [90]:
# 1.
np.random.choice([0, 1], size=10, replace=True)

In [ ]:
# 1.
np.random.choice(["H", "T"], size=10, replace=True)

In [91]:
# 2.
x = np.random.randint(1, 7, size=100)  # 시작점, 끝점
x.mean(),
np.mean(x)

3.41

In [ ]:
#2.
# np.random.randint(1, 7, 100)
# np.random.randint(1, 7, 100).mean()
np.random.choice(range(1,7), size=100, replace=True).mean()

In [87]:
# 3.
np.random.randn(250)  # 정규분포!
# 평균(기댓값)이 0이고, 표준편차가 1인 정규분포. 1% -> 0.01

array([-0.26089516, -1.49464313,  0.83332436, -0.29771005,  0.63691096,
       -1.38368487, -0.60942974, -1.83077942, -0.77919544,  0.89461092,
       -0.5544584 , -1.18814213,  0.56724765,  1.15315037,  0.9010615 ,
       -0.30860235,  0.86366189, -0.201526  ,  0.05235536,  0.48242568,
       -0.37134436,  0.52901791, -0.44788616, -0.33338223, -0.33871576,
        0.14772858, -0.20024487, -1.02397595,  0.0398592 , -3.09234795,
       -1.1707282 ,  0.04106505, -0.73727285, -1.09352086, -1.014161  ,
        0.58348329,  0.49065736,  0.54815781, -1.29708914,  0.26270223,
       -0.82140699, -0.61599629, -0.27953073,  0.24995909,  1.64901392,
        0.17818544,  0.13350883, -0.39389336, -0.19919594, -0.19581751,
       -0.01688324,  2.50250399, -0.26823193, -0.29432058, -0.15083477,
       -0.51334765, -0.50019511, -1.78039075,  0.64246727, -0.48808545,
        0.20312166,  1.42142296, -1.89704793, -0.57754466, -0.20606502,
        0.02475836, -0.24191347,  0.84551196, -0.14900842,  0.70

In [90]:
a = np.random.randn(250) / 100  # 일간 수익률이 표준정규분포를 따르는 (0과 0.01 표준편차)
a

array([-4.43266626e-03,  2.13281409e-02, -1.59504588e-02,  9.20339586e-03,
        6.46775108e-03, -2.31942114e-03, -8.59998277e-03, -7.70661263e-03,
       -2.69942025e-03,  1.07156435e-02,  4.46628707e-03, -1.09843009e-02,
       -5.06210903e-03, -1.14836131e-03, -7.99017278e-03,  7.94817798e-04,
        6.30076164e-03, -1.11873979e-02, -1.63704369e-03, -7.41381567e-03,
        1.54117039e-02, -8.76797480e-03, -1.21889947e-03, -1.21210863e-02,
        4.85783586e-03,  7.96164448e-03,  1.05988089e-03,  3.10120816e-04,
        1.40530363e-02,  2.52263342e-03,  3.78177411e-03,  1.02735600e-02,
       -4.64379666e-03,  1.10418727e-02,  5.57811329e-03,  7.87547713e-04,
        5.67146891e-03,  4.05387716e-03,  2.82834968e-03, -2.36161737e-03,
        4.53462807e-03, -1.47699400e-02, -1.79678618e-02, -2.88264142e-02,
        2.13871582e-04, -1.12568085e-02, -9.20205825e-04, -8.77926855e-03,
        6.19802580e-04, -5.27696049e-03,  2.47829335e-03, -1.71167575e-03,
        2.67755412e-02,  

In [93]:
start = 10000  # 가격이 10000원 -> 250일 -> 평균/표준편차가 반영되면서 250일.
price = np.empty(250)  # 자리
for i, v in enumerate(a): # a -> 가격이 0의 기댓값, 1%의 표준편차를 바탕으로 250일치의 변화율이 생성
    start *= (1 + v)  # i = index, v = 변화율
    # -> 해당 금액의 변화율이 반영된 금액
    price[i] = start  # 변화율에 따라서 변경된 금액에 배열에 저장.
    # 한 번씩 for이 돌때마다 -> index += 1 => 계속 변화율이 반영된 금액들이 다음 인덱스에 저장

In [92]:
price

array([9883.78137426, 9968.57944464, 9841.6186762 , 9594.4859386 ,
       9628.5438154 , 9595.06451168, 9570.28286851, 9618.5793089 ,
       9607.69352388, 9657.47644671, 9593.06802826, 9578.42084214,
       9501.72900862, 9513.94655308, 9443.023873  , 9368.48446257,
       9423.9520892 , 9404.46544522, 9461.52922411, 9463.1973051 ,
       9478.11109127, 9460.57910477, 9467.04002392, 9555.87570324,
       9529.10549585, 9559.16293926, 9403.7072512 , 9424.61992127,
       9387.65769273, 9361.49589267, 9206.11489445, 9192.63420828,
       9006.59774199, 9124.63469586, 9045.6423654 , 9036.69412953,
       9004.18975565, 8948.50714888, 8888.53302391, 8867.90444019,
       8839.50310416, 8795.81321081, 8711.92326963, 8607.5928555 ,
       8600.2082051 , 8659.26804041, 8567.17360292, 8482.71834255,
       8502.96278371, 8618.72244872, 8624.60912351, 8864.14211373,
       8790.8623261 , 9046.88062486, 9122.68960059, 9061.73325095,
       9168.66741536, 9205.45168589, 9164.26913988, 8974.09750

## 정수 데이터 카운팅
* 만약 난수가 정수값이면 unique 명령이나 bincount 명령으로 데이터 값을 분석

### `unique`
* unique 함수는 데이터에서 중복된 값을 제거하고 중복되지 않는 값의 리스트를 출력
* return_counts 인수를 True 로 설정하면 각 값을 가진 데이터 갯수도 출력


In [97]:
np.unique([11, 11, 2, 2, 34, 34]) #중복된 값을 제거하고 중복되지 않는 값의 리스트를 출력

array([ 2, 11, 34])

In [98]:
a = np.array(list('abbca'))
a

array(['a', 'b', 'b', 'c', 'a'], dtype='<U1')

In [112]:
np.unique(a, return_counts=True)

(array(['a', 'b', 'c'], dtype='<U1'), array([2, 2, 1]))

In [101]:
index, value = np.unique(a, return_counts=True)
index, value

(array(['a', 'b', 'c'], dtype='<U1'), array([2, 2, 1]))

In [ ]:
# dict(np.unique(a, return_counts=True))

In [95]:
index, value

In [104]:
list(zip(index, value))  # 같은 인덱스에 있는 값끼리 튜플화시켜서 묶어줌
# index, value == *np.unique(a, return_counts=True)

[('a', 2), ('b', 2), ('c', 1)]

In [105]:
dict(zip(*np.unique(a, return_counts=True)))  # key, value

{'a': 2, 'b': 2, 'c': 1}

### `bincount`
* `unique` 함수는 데이터에 존재하는 값에 대해서만 갯수를 세므로 데이터 값이 나올 수 있음에도 불구하고 데이터가 하나도 없는 경우에는 정보를 주지 않음
* 따라서 데이터가 주사위를 던졌을 때 나오는 수처럼 특정 범위안의 수인 경우에는 `bincount` 함수에 `minlength` 인수를 설정하여 쓰는 것이 더 편리
* `bincount` 함수는 0 부터 `minlength` - 1 까지의 숫자에 대해 각각 카운트
* 데이터가 없을 경우에는 카운트 값이 0이 됨

In [106]:
np.bincount([1, 1, 2, 2, 2, 3], minlength=6) # 1 = 2, 2 = 3, 3 = 1

array([0, 2, 3, 1, 0, 0])