<a href="https://colab.research.google.com/github/Chong5084/Colab_Note/blob/main/ch05_01_numpy_%EA%B8%B0%EC%B4%88_%EA%B3%B5%EC%9C%A0%EC%9A%A9_ipynb%EC%9D%98_%EC%82%AC%EB%B3%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy 기초

## 배열(Array)
* 많은 데이터를 하나의 변수에 넣는 법? : **리스트**
* 하지만 리스트는...
    * 속도가 느리다
    * 메모리를 많이 차지한다

> 그래서? **배열(Array)**을 사용한다

* 적은 메모리로 많은 데이터를 빠르게 처리할 수 있음

## 특징
1. 모든 원소가 같은 **자료형**이어야 함
2. 원소의 갯수를 바꿀 수 없음

> 그런데 파이썬은 자체적으로 배열 자료형을 제공하지 않음<br>
> 그래서 우리는 **넘파이(Numpy)** 패키지를 import해서 사용

In [3]:
# 파이썬 pip -> 외부 패키지 관리자 (툴들, 기능들 -> 패키지 -> 불러오기)
# 파이썬은 numpy가 내장이 아니기 때문에... -> pip install numpy
# 1. anaconda -> numpy가 딸려들어옴
# 2. colab -> numpy가 이미 설치
import numpy  # import 가져오기 -> 이미 설치된 numpy라는 기능을 가져오겠다...
# 너무 자주 쓰이기 때문에 numpy라는 전체 이름을 쓰지 않고 np라는 축약어를 사용
import numpy as np  # 다른 이름을 주지 마세요
# tap 입력시 자동입력
import numpy as np
# https://www.kaggle.com/
# https://dacon.io/
# https://datascienceschool.net/intro.html
# https://www.youtube.com/c/todaycode


## 1차원 배열
* 리스트나 튜플처럼 한 줄로 이루어진 형태의 배열

In [7]:
np.array([1, 2, 3]) # 마지막에 실행된 실행문의 결과를 아래 블록에 표시(변수명, 값 함수들)


array([1, 2, 3])

In [8]:
arr = np.array(range(10))
arr, type(arr)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), numpy.ndarray)

## ndarray
* 배열 객체 타입(자료형)
* 리스트와 동일해 보이지만 차이가 많음

|자료형|특징|
|:-|:-|
|리스트(list)|각각의 원소가 다른 자료형이 될 수 있음|
|배열(array)|연속적인 메모리 배치를 가지기 때문에 모든 원소가 같은 자료형이어야 함<br>원소에 대한 접근과 반복문 실행이 빨라짐|

<비유>
리스트(list) : 보따리
배열(array)	: 규격화 된 박스

In [11]:
import random

def average_python(n): # n개의 길이
    '''
    n개의 랜덤한 0~1 사이의 실수를 평균해주는 함수
    '''
    s = 0  # 총 합계
    for i in range(n):
        s += random.random()  # 총합
    return s / n  # 총합 / 갯수 => 산술 평균

# ctrl + enter => 한 개의 블록 실행 혹은 왼쪽 play button

In [12]:
%time average_python(100_000)  # %time : 시간 재기 -> 1번 실행

CPU times: user 18.9 ms, sys: 0 ns, total: 18.9 ms
Wall time: 18.9 ms


0.4991541676539473

In [13]:
%timeit average_python(100_000)  # %timeit : 시간 재기 (여러 번 실행)

22.9 ms ± 711 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [17]:
def average_numpy(n):
    'n개의 랜덤한 0~1 사이의 실수를 numpy를 사용해서 평균내는 함수'
    s = np.random.random(n)  # n개의 랜덤한 실수를 불러오는 numpy의 기능
    return s.mean()  # mean -> 평균 (mean, average)
# shift + enter : 현재 칸을 실행하고 다음 칸으로 넘어가기

In [18]:
%timeit average_numpy(100_000)

898 µs ± 13.3 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [20]:
%timeit average_numpy(100_000)
# 10^3 -> 10^7 us.

1.26 ms ± 336 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [21]:
# from ast import comprehension
# alt + enter : 새로운 코드블럭 생성 ( 윗 블럭 생성)
# shift + enter : 현재 칸을 실행하고 다음 칸으로 넘어가기
# 코드 복사 alt + shift + ↕

# python 3.11 <- 리스트의 속도가 상당히 빨라졌음
# list comprehension > numpt > list, for

## 벡터화 연산
* 배열 객체는 **배열의 각 원소에 대한 반복 연산을 하나의 명령어로 처리**하는 벡터화 연산(vectorized operation)을 지원

In [29]:
data = list(range(10))
data

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [27]:
# alt + enter
# 리스트 객체에 정수 곱하면?
data * 2  # 모든 원소에 2배가 됩니까?
# 리스트 객체에 정수를 곱하면 객체의 크기가 해당 정수 배만큼 증가 (n >= 1 클 때)

TypeError: ignored

In [ ]:
%%time
# %%time 전체 블록을 실행
# 여러 개의 데이터를 모두 2배 할 때 (파이썬)
answer = []
for d in data:
    answer.append(d * 2)
answer

CPU times: user 17 µs, sys: 0 ns, total: 17 µs
Wall time: 19.6 µs


[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [ ]:
%%timeit
# %%time 전체 블록을 실행
# 여러 개의 데이터를 모두 2배 할 때 (파이썬)
answer = []
for d in data:
    answer.append(d * 2)
answer

CPU times: user 17 µs, sys: 0 ns, total: 17 µs
Wall time: 19.6 µs


[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [30]:
%%time
# 리스트 컴프리헨션
[d * 2 for d in data]

CPU times: user 3 µs, sys: 0 ns, total: 3 µs
Wall time: 7.63 µs


In [ ]:
%%timeit
# 리스트 컴프리헨션
[d * 2 for d in data]

CPU times: user 3 µs, sys: 0 ns, total: 3 µs
Wall time: 7.63 µs


In [33]:
# 벡터화 연산
arr = np.array(data) # 시퀀스 형태의 데이터를 np.array -> numpy 배열
arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
%time arr *2 # 배열

In [36]:
%%timeir arr *2 # 배열

UsageError: Cell magic `%%timeir` not found.


In [ ]:
# 3.9 버전까지는 웬만하면 numpy 압살 -> 3.10 (속)

In [37]:
# 리스트 객체에 정수를 곱하면 객체의 크기가 해당 정수 배만큼 증가
data * 3 # repeat 연산(반복연산)

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9]

* 벡터화 연산은 비교 연산과 논리 연산을 포함한 모든 종류의 수학 연산에 대해 적용

In [40]:
 a = np.array(range(1, 4))
 b =np.array(range(10, 40, 10))
 a, b

(array([1, 2, 3]), array([10, 20, 30]))

In [42]:
a * 10

array([10, 20, 30])

In [43]:
a * 2 + b # 백터화 연산을 통핸 산술연산

array([12, 24, 36])

In [45]:
a ** 2, b ** 0.5

(array([1, 4, 9]), array([3.16227766, 4.47213595, 5.47722558]))

In [47]:
 a== 2, b >10

(array([False,  True, False]), array([False,  True,  True]))

In [49]:
 a== 2, b >10, b <= 10 # 비교연산이 된다는 것은? 논리연산도 가능하다.

(array([False,  True, False]),
 array([False,  True,  True]),
 array([ True, False, False]))

In [55]:
# & : and 연산
'''
array([False,  True, False])
(array([False,  True, False]), array([False,  True,  True]))
'''
(a == 2) & ( b > 10)  # 논리 연산
(a == 2) & (b > 10), (a == 2) | (b > 10)


(array([False,  True, False]), array([False,  True,  True]))

## 2차원 배열
* `ndarray`는 N-dimensional Array의 약자, 즉 1차원 배열 이외에도 2차원 배열, 3차원 배열 등의 다차원 배열 자료 구조를 지원
* 2차원 배열 = 행렬 (matrix)
* 가로줄 : 행(row), 세로줄 : 열(column)
> 엑셀 스프레드시트와 같은 형태의 배열

* 리스트의 리스트(list of list)를 이용하여 2차원 배열 생성
    * 안쪽 리스트의 길이 : 행렬의 열의 수 (가로 크기)
    * 바깥쪽 리스트의 길이 : 행렬의 행의 수 (세로 크기)

In [58]:
arr = np.array([[0, 1, 2], [3, 4, 5]])
arr
'''
arr = np.array([[0, 1, 2],   #  2개의 형(가로)
                [3, 4, 5]])  #  3개의 열(세로)

'''

array([[0, 1, 2],
       [3, 4, 5]])

In [61]:
# 행의 갯수, 열의 갯수 구하는 코드
len(arr), len(arr[0]) # (2, 3)
len(arr), len(arr[0]), len(arr[1]) # (2, 3, 3)

(2, 3, 3)

## 💡 연습문제 1
> 아래 모양의 행렬 만들어 보기
```
10 20 30 40
50 60 70 80
```

In [67]:
array = np.array([[10, 20, 30, 40], [50, 60, 70, 80]]) # 보이는 데로
array

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [69]:
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8]]) * 10 # 간결화 하되 벡터연산으로
array

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [72]:
np.array([[(a * 4 + (b + 1)) * 10 for b in range(4)] for a in range(2)])
# 이런것도 된다 뜯어 보고 Ai한테 물어보기
# 파이선 초심자도 이해하기 쉽게 쪼개서 설명해줘

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [66]:
len(array), len(array[0]) # (2, 4) 2개의 열(가로), 4개의 행(세로)

(2, 4)

## 3차원 배열

In [78]:
# 크기를 나타낼 때는 가장 바깥쪽 리스트의 길이부터 가장 안쪽 리스트 길이의 순서로 표시
# m : matrix (2차원 배열 행렬)
# t : three-dimention
# 코드 복사 alt + shift + ↕
 t = np.array(
    [
        [
            [1, 2, 3, 4],
            [5, 6, 7, 8],
            [9, 10, 11, 12],
        ],
        [
            [11, 12, 13, 14],
            [15, 16, 17, 18],
            [19, 20, 21, 22],
        ],  # 4개
    ]  # 가장 밖 리스트 -> 요소 2개
)
t

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22]]])

In [77]:
# 깊이, 행, 열
len(t), len(t[0]), len(t[0][0])


(2, 3, 4)

## 배열의 차원과 크기 알아내기
* `ndim`, `shape` **속성** 사용
> 속성 : 괄호 없이 이름만 써서 값을 호출

* `ndim` : 배열의 차원
* `shape` : 배열의 크기

In [82]:
a = np.array(range(1, 4))
a

array([1, 2, 3])

In [83]:
a.ndim, a.shape  # 1차원

(1, (3,))

In [87]:
m = np.array((range(3), range(3, 6))) # 3개 3개
m

array([[0, 1, 2],
       [3, 4, 5]])

In [89]:
m.ndim, m.shape  #2차원

(2, (2, 3))

In [91]:
t.ndim, t.shape  #3차원

(3, (2, 3, 4))

## 배열의 복사
* copy와 view의 차이점은 copy는 새 배열(깊은 복사)이고 view는 원래 배열과 연결 되어 있다는 것(얕은 복사)
* copy는 데이터를 소유하며 copy에 대한 변경 사항은 원본 배열에 영향을 미치지 않으며 원본 배열에 대한 변경은 copy에 영향을 주지 않음
* view는 데이터를 소유하지 않으며 view에 대한 모든 변경 사항은 원래 배열에 영향을 미치고 원래 배열에 대한 모든 변경 사항은 보기에 영향을 줌

In [92]:
arr = np.array(range(1, 6))
arr2 = arr # 복사 -> 할당 또는 대입이라 함
arr[0] = 40 # 0번째 자리를 40으로 바뀜
arr, arr2 # arr2도 arr과 같이 바뀜


(array([40,  2,  3,  4,  5]), array([40,  2,  3,  4,  5]))

In [94]:
arr = np.array(range(1, 6))
arr2 = arr.view() # 읽기 전용의 사본 (일부러 원본과 연결된 사본)
# 얕은 복사도 깊은 복사도 아님
arr[0] = 40
arr, arr2


(array([40,  2,  3,  4,  5]), array([40,  2,  3,  4,  5]))

In [97]:
arr = np.array(range(1, 6))
arr2 = arr.copy() # 얕은복사x <- 깊은 복사
arr[0] = 40
arr, arr2


(array([40,  2,  3,  4,  5]), array([1, 2, 3, 4, 5]))

In [100]:
arr3 = np.array([arr, arr])  # np.array로 만들어지면서 완전하 사본
arr4 = arr3.copy()
arr3, arr4

(array([[41,  2,  3,  4,  5],
        [41,  2,  3,  4,  5]]),
 array([[41,  2,  3,  4,  5],
        [41,  2,  3,  4,  5]]))

In [101]:
arr[0] = 41
arr4[0] = 43
arr3, arr4

(array([[41,  2,  3,  4,  5],
        [41,  2,  3,  4,  5]]),
 array([[43, 43, 43, 43, 43],
        [41,  2,  3,  4,  5]]))

## 배열의 인덱싱

### 일차원 배열
* 리스트의 인덱싱과 같음

In [103]:
a = np.array(range(5))
print(a) # 1차원 배열
a[0], a[2],a[-1], a[len(a)-1]

[0 1 2 3 4]


(0, 2, 4, 4)

### 다차원 배열 / 2차원 이상의 배열
* 콤마(comma, `,`)를 사용하여 접근
* 콤마로 구분된 차원을 축(axis)라고 함
    * like 그래프의 x축, y축

In [109]:
b = np.array([range(3), range(3, 6)])
b, b.ndim, b.shape

(array([[0, 1, 2],
        [3, 4, 5]]),
 2,
 (2, 3))

In [115]:
# b[0][0] # 첫번째 행의 첫번째 열 /일반 리스트에서는 실행 x
b[0, 0] #  np.array로 만든것에 한에서

0

In [114]:
# 첫번째 행의 2번째 열
b[0, 1]

1

In [116]:
# 마지막 행의 마지막열
b[-1,-1]

5

## 배열 슬라이싱
* 다차원 배열의 원소 중 2개 이상의 복수 개를 접근하려면 일반적인 파이썬 슬라이싱(slicing)과 comma(,)를 함께 사용

In [117]:
a = np.array([range(4), range(4,8)])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [118]:
# a[0] 즉 첫 번째 행의 전체열
a[0], a[0,:]

(array([0, 1, 2, 3]), array([0, 1, 2, 3]))

In [127]:
# 두 번째 열의 모든 행 (모든 행의 두 번째 열)
a[:, 1]

array([1, 5])

In [128]:
# 두 번째 행의, 두 뻔째 열부터 끝까지?
a[:2, :2]  # a[0:2, 0:2]

array([5, 6, 7])

In [131]:
# 첫 번째 행에서 두번째 행까지, 첫 번째 열에서 두 번쨰 열까지
a[:2]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

## 💡 연습문제 2

In [137]:
m = np.array([[0,  1,  2,  3,  4],
              [5,  6,  7,  8,  9],
              [10, 11, 12, 13, 14]])
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [146]:
#@markdown (1) 값 7을 인덱싱
m[1][2],
m[1, 2],
m[1, -3],
m[-2, 2],
m[-2, -3]

7

In [150]:
#@markdown (2) 값 14을 인덱싱
m[2, 4], m[2][4], m[2,-1], m[-1,-1]

(14, 14, 14, 14)

In [253]:
#@markdown (3) 배열 [6,7]을 슬라이싱
m[1,1:3], m[1][1:3], m[-2,1:3], m[-2][1:3]

(array([6, 7]), array([6, 7]), array([6, 7]), array([6, 7]))

In [ ]:
# 강사님풀이
#@markdown (3) 배열 [6,7]을 슬라이싱
m[1, 1:3], m[-2, 1:3], m[1, -4:-2], m[-2, -4:-2]  # 같은 행에서 열을 인덱스

In [252]:
#@markdown (4) 배열 [7,12]을 슬라이싱
m[1,2],m[2,2], m[:1, 2]

(7, 12, array([2]))

In [ ]:
#강사님풀이
#@markdown (4) 배열 [7,12]을 슬라이싱
# 같은 열 -> 행을.
m[1:, 2], m[-2:, 2], m[1:, -3], m[-2:, -3]

In [256]:
#@markdown (5) 배열 [[3,4],[8,9]]을 슬라이싱
m[:2, 3:5], m[-1: -1:-2]

(array([[3, 4],
        [8, 9]]),
 array([], shape=(0, 5), dtype=int64))

In [257]:
#강사님풀이
#@markdown (5) 배열 [[3,4],[8,9]]을 슬라이싱
print(m[:2,3:])
print(m[:-1,3:])
print(m[:2,-2:])
print(m[:-1,-2:])

[[3 4]
 [8 9]]
[[3 4]
 [8 9]]
[[3 4]
 [8 9]]
[[3 4]
 [8 9]]


## 배열 인덱싱
* 대괄호(Bracket, [])안의 인덱스 정보로 숫자나 슬라이스가 아니라 위치 정보를 나타내는 또다른 `ndarray` 배열을 받을 수 있음 (인덱스 배열)
* 일종의 조건 검색 기능

### 불리언 (Boolean) 배열 인덱싱
* 인덱스 배열의 원소가 True, False 두 값으로만 구성되며 인덱스 배열의 크기가 원래 ndarray 객체의 크기와 같아야 함

In [259]:
# 0~8 사이의 (끝포함) 짝수만 가진 배열
a1 = np.array(range(0, 9, 2))
# a2 = np.array([i for i in range(0, 9) if i % 2 == 0])
a2 = np.array([i for i in range(0, 9) if not i % 2])
a3 = np.array(range(9))[::2]  # 배열 슬라이싱도 증가폭이 된다
a1, a2, a3

(array([0, 2, 4, 6, 8]), array([0, 2, 4, 6, 8]), array([0, 2, 4, 6, 8]))

In [258]:
# 짝수인 원소만 골라내고 싶다면?
# 짝수에 대응하는 곳에 True, 홀수에 대응하는 곳에 False
a = np.array(range(10))
a

In [260]:
# idx = np.array[(True, False, True, False, True, False, True, False, True, False])
idx = np.array([i % 2 == 0 for i in range(10)])
idx

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [270]:
a[idx]  # 내가 보기를 원하는 곳만 True를 넣어놓은 배열을 [] 안에 넣으니까...
# 필터링

IndexError: ignored

In [267]:
# 조건문 연산
a % 2

array([[0, 1, 0, 1],
       [0, 1, 0, 1]])

In [268]:
a % 2 == 0 # 불리언 인덱스 배열 <- 비교연산

array([[ True, False,  True, False],
       [ True, False,  True, False]])

In [265]:
a[a % 2 == 0]

array([0, 2, 4, 6])

In [266]:
a[a % 3 == 0], a[a % 3 != 0], a[a // 2 == 1]

(array([0, 3, 6]), array([1, 2, 4, 5, 7]), array([2, 3]))

### 정수 배열 인덱싱
* 인덱스 배열의 원소 각각이 원래 `ndarray` 객체 원소 하나를 가리키는 인덱스 정수이여야 함

In [272]:
a = np.array(range(1, 10)) * 11
a

array([11, 22, 33, 44, 55, 66, 77, 88, 99])

In [274]:
# 0, 2, 4, 6, 8 ->인덱스해서 가져오고 슾음
idx = np.array([ 0, 2, 4, 6, 8])
a[idx]

array([11, 33, 55, 77, 99])

In [275]:
# 0, 2, 4, 6, 8 ->인덱스해서 가져오고 슾음
idx = np.array([ 0, 2, 4, 6, 8])
a[idx], a[[0, 2, 4, 6, 8 ]]

(array([11, 33, 55, 77, 99]), array([11, 33, 55, 77, 99]))

* 이 때는 배열 인덱스의 크기가 원래의 배열 크기와 달라도 상관없음
* 같은 원소를 반복해서 가리키는 경우에는 배열 인덱스가 원래의 배열보다 더 커지기도 함

In [276]:
idx = np.array([0] * 6 + [1] * 5 + [2] * 5)
print(idx)
a[idx]  # 해당 인덱스가 반복해서 등장

[0 0 0 0 0 0 1 1 1 1 1 2 2 2 2 2]


array([11, 11, 11, 11, 11, 11, 22, 22, 22, 22, 22, 33, 33, 33, 33, 33])

### 다차원 배열에서의 배열 인덱싱

In [281]:
a = np.array([range(1,5), range(5,9),range(9, 13)])
a, a.ndim, a.shape

(array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 2,
 (3, 4))

In [287]:
print(a[:, [0,3]])
# print(a[:, [3,0]])
print(a[:, [0,-1]])
print(a[:, [True, False, True, False]])
print(a[:, [i % 2 == 0 for i in range(4)]])

[[ 1  4]
 [ 5  8]
 [ 9 12]]
[[ 1  4]
 [ 5  8]
 [ 9 12]]
[[ 1  3]
 [ 5  7]
 [ 9 11]]
[[ 1  3]
 [ 5  7]
 [ 9 11]]


In [289]:
# 행을 하게 되면?
a[[2, 0, 1], :]

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

## 💡 연습문제 3

In [313]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [338]:
# (1) 3의 배수 찾기
x = np.array(range(0, 19, 3))
x

array([ 0,  3,  6,  9, 12, 15, 18])

In [347]:
# (2) 4로 나누면 1이 남는 수 찾기
x[x % 4 == 1]
# x[x // 4 == 1]

array([9])

In [335]:
# (3) 3로 나누면 나누어지고 4로 나누면 1이 남는 수 찾기
x[x % 4 == 1]

(array([9]), [array([0., 1., 2., 3., 4., 5., 6.])])

## 배열 검색

In [290]:
arr = np.array([1,2,3,4,5,4,4])
arr

array([1, 2, 3, 4, 5, 4, 4])

In [292]:
# np.array(배열 비교/논리 연산) -> 조건을 만족시킨 값의 인덱스 반환
x = np.array(arr ==4)
x, arr[x]

(array([False, False, False,  True, False,  True,  True]), array([4, 4, 4]))

In [301]:
'''
1.
2. 조건을 만족하는
3. np.where을 사용 해서 인덱스
'''
arr = np.array(range(1, 9))
print(arr)
x = np.where(arr % 2 == 0) # 짝수 <- 나오게 인덱스
x, arr[x], arr[arr % 2 == 0]


[1 2 3 4 5 6 7 8]


((array([1, 3, 5, 7]),), array([2, 4, 6, 8]), array([2, 4, 6, 8]))

In [306]:
a = np.array(range(100, 1000, 100)) # 9개
b = [ i + "파이썬" for i in "김이박최류유조송"]
np.where(a % 200 == 0)

(array([1, 3, 5, 7]),)

In [307]:
a = np.array(range(100, 1000, 100)) # 9개
b = np.array([ i + "파이썬" for i in "김이박최류유조송"])
np.where(a % 200 == 0)

(array([1, 3, 5, 7]),)